# Serverless ALL
plugins:
  - serverless-plugin-typescript
  - serverless-offline

service: boilerplatelambda

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  stage: samuel

functions:
  all:
    handler: src/lambda/main.all
    events:
      - http:
          path: /main/all
          method: GET
  add:
    handler: src/lambda/main.add
    events:
      - http:
          path: /main/
          method: POST
  update:
    handler: src/lambda/main.update
    events:
      - http:
          path: /main/{id}
          method: PUT
  remove:
    handler: src/lambda/main.remove
    events:
      - http:
          path: /main/{id}
          method: DELETE