# Serverless ALL
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-openapi-documentation

service: boilerplatelambda

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  stage: samuel

# serverless openapi generate
custom:
  documentation:
    version: '1.0.0'
    title: 'My Rest Main API'
    description: 'This is my API'
    models:
      - name: "GetMainResponse"
        description: "Get Main Entities"
        contentType: "application/json"
        schema:
          $schema: "http://json-schema.org/draft-04/schema#"
          title : "Main"
          type : "array"
          items:
            type: integer
functions:
  all:
    handler: src/lambda/main.all
    events:
      - http:
          path: /main/all
          method: GET
          documentation:
            summary: Get all
            description: Get all elements in database
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "All Main entities"
                responseModels:
                  application/json: "GetMainResponse"
  add:
    handler: src/lambda/main.add
    events:
      - http:
          path: /main/
          method: POST
  update:
    handler: src/lambda/main.update
    events:
      - http:
          path: /main/{id}
          method: PUT
  remove:
    handler: src/lambda/main.remove
    events:
      - http:
          path: /main/{id}
          method: DELETE